//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTONKHO
    {
        public string MaBCTK { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public string MaHH { get; set; }
        public Nullable<int> TonDau { get; set; }
        public Nullable<int> TonCuoi { get; set; }
        public Nullable<int> SoLuongNhapThem { get; set; }
        public Nullable<int> SoLuongXuatRa { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
