//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUHEO
    {
        public string SoPhieu { get; set; }
        public string MaHeo { get; set; }
        public Nullable<int> TrongLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual HEO HEO { get; set; }
        public virtual PHIEUHEO PHIEUHEO { get; set; }
    }
}
