//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.BAOCAOTONKHOes = new HashSet<BAOCAOTONKHO>();
            this.CT_PHIEUHANGHOA = new HashSet<CT_PHIEUHANGHOA>();
            this.CT_PHIEUKIEMKHO = new HashSet<CT_PHIEUKIEMKHO>();
            this.QuyDinhTiemHeos = new HashSet<QuyDinhTiemHeo>();
        }
    
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
        public string TinhTrang { get; set; }
        public string LoaiHangHoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOTONKHO> BAOCAOTONKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUHANGHOA> CT_PHIEUHANGHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUKIEMKHO> CT_PHIEUKIEMKHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyDinhTiemHeo> QuyDinhTiemHeos { get; set; }
    }
}
