//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCHUONG
    {
        public string MaChuong { get; set; }
        public System.DateTime NgayLam { get; set; }
        public string TrangThai { get; set; }
        public string TenLich { get; set; }
        public string Mota { get; set; }
        public string MaNguoiTao { get; set; }
        public string MaNguoiLam { get; set; }
    
        public virtual CHUONGTRAI CHUONGTRAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
