//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTIEMHEO
    {
        public string MaLichTiem { get; set; }
        public string MaHeo { get; set; }
        public string MaThuoc { get; set; }
        public Nullable<System.DateTime> NgayTiem { get; set; }
        public Nullable<int> LieuLuong { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HEO HEO { get; set; }
    }
}
