//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRANGTRAINUOIHEOEntities : DbContext
    {
        public TRANGTRAINUOIHEOEntities()
            : base("name=TRANGTRAINUOIHEOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAOTONKHO> BAOCAOTONKHOes { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CHUONGTRAI> CHUONGTRAIs { get; set; }
        public virtual DbSet<CT_PHIEUHANGHOA> CT_PHIEUHANGHOA { get; set; }
        public virtual DbSet<CT_PHIEUHEO> CT_PHIEUHEO { get; set; }
        public virtual DbSet<CT_PHIEUKIEMKHO> CT_PHIEUKIEMKHO { get; set; }
        public virtual DbSet<CT_PHIEUSUACHUA> CT_PHIEUSUACHUA { get; set; }
        public virtual DbSet<DOITAC> DOITACs { get; set; }
        public virtual DbSet<GIONGHEO> GIONGHEOs { get; set; }
        public virtual DbSet<HANGHOA> HANGHOAs { get; set; }
        public virtual DbSet<HEO> HEOs { get; set; }
        public virtual DbSet<LICHCHUONG> LICHCHUONGs { get; set; }
        public virtual DbSet<LICHPHOIGIONG> LICHPHOIGIONGs { get; set; }
        public virtual DbSet<LICHTIEMHEO> LICHTIEMHEOs { get; set; }
        public virtual DbSet<ListActionDetail> ListActionDetails { get; set; }
        public virtual DbSet<LOAICHUONG> LOAICHUONGs { get; set; }
        public virtual DbSet<LOAIHEO> LOAIHEOs { get; set; }
        public virtual DbSet<MuaDichBenh> MuaDichBenhs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PERMISION> PERMISIONs { get; set; }
        public virtual DbSet<PERMISION_DETAIL> PERMISION_DETAIL { get; set; }
        public virtual DbSet<PHIEUHANGHOA> PHIEUHANGHOAs { get; set; }
        public virtual DbSet<PHIEUHEO> PHIEUHEOs { get; set; }
        public virtual DbSet<PHIEUKIEMKHO> PHIEUKIEMKHOes { get; set; }
        public virtual DbSet<PHIEUSUACHUA> PHIEUSUACHUAs { get; set; }
        public virtual DbSet<QuyDinhTiemHeo> QuyDinhTiemHeos { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
    }
}
