//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISION_DETAIL
    {
        public string ID_PermisionDetail { get; set; }
        public string ActionDetail { get; set; }
        public string PermisionDetail_Descript { get; set; }
        public string ID_Permision { get; set; }
    
        public virtual PERMISION PERMISION { get; set; }
    }
}
