//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinhTiemHeo
    {
        public string MaTiemHeo { get; set; }
        public string MaVaxin { get; set; }
        public Nullable<int> TuoiTiem { get; set; }
        public string MoTa { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
