//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int id { get; set; }
        public Nullable<int> XuatChuongMin { get; set; }
        public Nullable<int> XuatChuongMax { get; set; }
        public Nullable<int> MonthXuatChuongMin { get; set; }
        public Nullable<int> MonthXuatChuongMax { get; set; }
        public Nullable<int> TuoiNhapDan { get; set; }
        public Nullable<int> CanHuyet { get; set; }
        public Nullable<int> TuoiPhoiGiongDuc { get; set; }
        public Nullable<int> TuoiPhoiGiongCai { get; set; }
        public Nullable<int> RePhoiGiongDuc { get; set; }
        public Nullable<int> RePhoiGiongCai { get; set; }
        public Nullable<int> ThucAnMotNgay { get; set; }
        public Nullable<int> ThucAnMax { get; set; }
    }
}
