//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagementSoftware.Model
{
    using FarmManagementSoftware.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class CT_PHIEUKIEMKHO : BaseViewModel
    {
        public string SoPhieu { get; set; }
        public string MaHangHoa { get; set; }
        public Nullable<int> SoLuongHienCo { get; set; }
        private Nullable<int> SoLuongKiemTra { get; set; }
        public Nullable<int> _soLuongKiemTra { get => SoLuongKiemTra; set { SoLuongKiemTra = value; OnPropertyChanged(); } }

        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUKIEMKHO PHIEUKIEMKHO { get; set; }
    }
}
