//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagementSoftware.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.LICHCHUONGs = new HashSet<LICHCHUONG>();
            this.LICHCHUONGs1 = new HashSet<LICHCHUONG>();
            this.PHIEUHEOs = new HashSet<PHIEUHEO>();
            this.PHIEUHANGHOAs = new HashSet<PHIEUHANGHOA>();
            this.PHIEUHANGHOAs1 = new HashSet<PHIEUHANGHOA>();
            this.PHIEUKIEMKHOes = new HashSet<PHIEUKIEMKHO>();
            this.PHIEUSUACHUAs = new HashSet<PHIEUSUACHUA>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.ThongBaos1 = new HashSet<ThongBao>();
        }
    
        public string MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public byte[] BytesImage { get; set; }
        public string MaChucVu { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string email { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public string TrangThai { get; set; }
        public string C_Username { get; set; }
        public string C_PassWord { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHCHUONG> LICHCHUONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHCHUONG> LICHCHUONGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUHEO> PHIEUHEOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUHANGHOA> PHIEUHANGHOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUHANGHOA> PHIEUHANGHOAs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUKIEMKHO> PHIEUKIEMKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUSUACHUA> PHIEUSUACHUAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos1 { get; set; }
    }
}
